# basics

$$a=(b+c)*(c+2)$$

![title](graph.png)
* http://adventuresinmachinelearning.com/python-tensorflow-tutorial/

In [1]:
import tensorflow as tf
import numpy as np

# first, create a TensorFlow constant
const = tf.constant(2.0, name="const")
    
# create TensorFlow variables
#b = tf.Variable(2.0, name='b')
b = tf.placeholder(tf.float32, [None, 1], name='b')
c = tf.Variable(1.0, name='c')

In [2]:
# now create some operations
d = tf.add(b, c, name='d')
e = tf.add(c, const, name='e')
a = tf.multiply(d, e, name='a')
# create TensorFlow variables


In [3]:
# setup the variable initialisation
init_op = tf.global_variables_initializer()

In [4]:

sess = tf.Session()

sess.run(init_op)
'''d__ = sess.run(d)
e__ = sess.run(e)
a__= sess.run(a)'''
a_out = sess.run(a, feed_dict={b: np.arange(0, 10)[:, np.newaxis]})
#print("a:{0}\td:{1}\te:{2}\ta_out:{3}".format(a__,d__,e__,a_out))
print(a_out)


[[  3.]
 [  6.]
 [  9.]
 [ 12.]
 [ 15.]
 [ 18.]
 [ 21.]
 [ 24.]
 [ 27.]
 [ 30.]]


In [5]:
np.arange(0, 10)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
es = 2 * np.random.random((10,10)) - 1
#na = 2 * np.random.random((10,10)) - 1
na = 2 * np.random.random((10,10)) - 1

In [9]:
es

array([[-0.25888717,  0.70692996,  0.65641436,  0.91002234, -0.65511653,
        -0.83740614,  0.08041791, -0.27470505,  0.42892816, -0.25795315],
       [-0.1731005 , -0.8618791 , -0.29711146,  0.03905007, -0.11197005,
        -0.04071068, -0.79174131,  0.49262257, -0.41013372,  0.33698786],
       [ 0.7590609 ,  0.64488972, -0.22299351, -0.09060236, -0.57465121,
        -0.54164187, -0.07980234,  0.33823811,  0.49595729,  0.32578563],
       [-0.70506795, -0.32959265,  0.31740872,  0.83245595,  0.91248516,
        -0.45019427,  0.40152685, -0.79669302,  0.06272229,  0.14994694],
       [-0.23715019,  0.51056293, -0.72926826,  0.11868649, -0.56441299,
         0.80881226, -0.54443467,  0.28230599, -0.81363129,  0.68379981],
       [-0.35216006, -0.60203798,  0.94063279, -0.71393632, -0.31155569,
        -0.14737688, -0.33514176,  0.62354797, -0.98992824,  0.08274143],
       [-0.43760402,  0.42151217, -0.31622573,  0.35572644,  0.85487106,
        -0.32678098, -0.50471705,  0.54030833

In [10]:
na

array([[-0.5497732 , -0.74075813,  0.85867326,  0.20653296, -0.94428842,
        -0.12839527,  0.70007896,  0.48696955,  0.4924178 ,  0.3394367 ],
       [ 0.04755355,  0.34334039, -0.03773734, -0.14335172,  0.77424309,
        -0.83355151,  0.82911297, -0.26703797,  0.50165295,  0.53624487],
       [ 0.5072339 , -0.98434892,  0.36953574, -0.73052315,  0.85035728,
        -0.47239209, -0.99716974,  0.03535028, -0.5864477 , -0.03730089],
       [-0.72421699, -0.71501411, -0.92268971,  0.04892027,  0.57253883,
        -0.49788716, -0.98313872,  0.32728545,  0.51584819, -0.4715762 ],
       [ 0.71094349, -0.32565187, -0.03779834, -0.22811558, -0.03574759,
        -0.19226692,  0.97776928, -0.27265856, -0.89359133, -0.73399101],
       [ 0.20671769,  0.38600549,  0.90523088, -0.3463122 ,  0.74389341,
         0.22674473,  0.44235981,  0.55383675, -0.60978536, -0.12396672],
       [-0.83539877, -0.80299179,  0.54996123,  0.42142056, -0.43766174,
        -0.87109669,  0.31636511,  0.62051656

https://stackoverflow.com/questions/41704484/what-is-difference-between-tf-truncated-normal-and-tf-random-normal#43726140

In [11]:
# Neural network variables
learning_rate = 0.5
epochs = 10
batch_size = 100

NODES_INPUT = 10
NODES_H1 = 15
NODES_H2 = 15
NODES_OUPUT = 10



In [12]:
# entrada: x -> español
# salida: y -> náhuatl
es = tf.placeholder(tf.float64,[None,NODES_INPUT])
na = tf.placeholder(tf.float64,[None,NODES_OUPUT])

In [13]:
W1 = tf.Variable(tf.random_normal([NODES_INPUT,NODES_H1],stddev=0.01),name = 'W1')
b1 = tf.Variable(tf.random_normal([NODES_H1]), name = 'b1')

W2 = tf.Variable(tf.random_normal([NODES_H1,NODES_OUPUT],stddev=0.01),name = 'W2')
b2 = tf.Variable(tf.random_normal([NODES_OUPUT]), name = 'b2')
