# basics

$$a=(b+c)*(c+2)$$

![title](graph.png)

* http://adventuresinmachinelearning.com/python-tensorflow-tutorial/
* http://adventuresinmachinelearning.com/neural-networks-tutorial/


In [1]:
import tensorflow as tf
import numpy as np

# first, create a TensorFlow constant
const = tf.constant(2.0, name="const")
    
# create TensorFlow variables
#b = tf.Variable(2.0, name='b')
b = tf.placeholder(tf.float32, [None, 1], name='b')
c = tf.Variable(1.0, name='c')

In [2]:
# now create some operations
d = tf.add(b, c, name='d')
e = tf.add(c, const, name='e')
a = tf.multiply(d, e, name='a')
# create TensorFlow variables


In [3]:
# setup the variable initialisation
init_op = tf.global_variables_initializer()

In [4]:

sess = tf.Session()

sess.run(init_op)
'''d__ = sess.run(d)
e__ = sess.run(e)
a__= sess.run(a)'''
a_out = sess.run(a, feed_dict={b: np.arange(0, 10)[:, np.newaxis]})
#print("a:{0}\td:{1}\te:{2}\ta_out:{3}".format(a__,d__,e__,a_out))
print(a_out)


[[  3.]
 [  6.]
 [  9.]
 [ 12.]
 [ 15.]
 [ 18.]
 [ 21.]
 [ 24.]
 [ 27.]
 [ 30.]]


In [29]:
np.arange(0, 10)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [109]:
es = 2 * np.random.random((10,15)) - 1
#na = 2 * np.random.random((10,10)) - 1
na = 2 * np.random.random((10,1)) -2


In [110]:
es

array([[ 0.13608912,  0.85119328, -0.85792788, -0.8257414 , -0.95956321,
         0.66523969,  0.5563135 ,  0.7400243 ,  0.95723668,  0.59831713,
        -0.07704128,  0.56105835, -0.76345115,  0.27984204, -0.71329343],
       [ 0.88933783,  0.04369664, -0.17067612, -0.47088878,  0.54846738,
        -0.08769934,  0.1368679 , -0.9624204 ,  0.23527099,  0.22419145,
         0.23386799,  0.88749616,  0.3636406 , -0.2809842 , -0.12593609],
       [ 0.39526239, -0.87954906,  0.33353343,  0.34127574, -0.57923488,
        -0.7421474 , -0.3691433 , -0.27257846,  0.14039354, -0.12279697,
         0.97674768, -0.79591038, -0.58224649, -0.67738096,  0.30621665],
       [-0.49341679, -0.06737845, -0.51114882, -0.68206083, -0.77924972,
         0.31265918, -0.7236341 , -0.60683528, -0.26254966,  0.64198646,
        -0.80579745,  0.67588981, -0.80780318,  0.95291893, -0.0626976 ],
       [ 0.95352218,  0.20969104,  0.47852716, -0.92162442, -0.43438607,
        -0.75960688, -0.4077196 , -0.76254456, 

In [111]:
np.ceil(na)

array([[-0.],
       [-0.],
       [-0.],
       [-0.],
       [-1.],
       [-1.],
       [-0.],
       [-1.],
       [-0.],
       [-1.]])

https://stackoverflow.com/questions/41704484/what-is-difference-between-tf-truncated-normal-and-tf-random-normal#43726140

In [80]:
# Neural network variables
learning_rate = 0.1
epochs = 10
batch_size = 100

NODES_INPUT = 15
NODES_H1 = 11
NODES_H2 = 15
NODES_OUPUT = 10



In [81]:
# entrada: x -> español
# salida: y -> náhuatl
#es = tf.placeholder(tf.float64,[None,NODES_INPUT])
#na = tf.placeholder(tf.float64,[None,NODES_OUPUT])

es = tf.placeholder(shape=[None,NODES_INPUT], dtype=tf.float32)
na = tf.placeholder(shape=[None,NODES_OUPUT], dtype=tf.float32)

In [82]:
# capa oculta
W1 = tf.Variable(tf.random_normal([NODES_INPUT,NODES_H1],stddev=0.01),name = 'W1')
b1 = tf.Variable(tf.random_normal([NODES_H1]), name = 'b1')
# capa de salida
W2 = tf.Variable(tf.random_normal([NODES_H1,NODES_OUPUT],stddev=0.01),name = 'W2')
b2 = tf.Variable(tf.random_normal([NODES_OUPUT]), name = 'b2')


In [83]:
# calcular salida de capa oculta
# h(x) = x*W + bias
hidden_output = tf.add(tf.matmul(es, W1), b1)
# función de activación ReLU
hidden_output = tf.nn.relu(hidden_output)

In [84]:
# calcular salida la NN
na_predicted = tf.nn.softmax(tf.add(tf.matmul(hidden_output, W2),b2))

In [90]:
# costo
y_clipped = tf.clip_by_value(na_predicted, 1e-10, 0.9999999)
cross_entropy = -tf.reduce_mean(tf.reduce_sum(na * tf.log(y_clipped)
                         + (1 - na) * tf.log(1 - y_clipped), axis=1))

In [91]:
# optimiser
optimiser = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cross_entropy)

In [93]:
# finally setup the initialisation operator
init_op = tf.global_variables_initializer()

# define an accuracy assessment operation
correct_prediction = tf.equal(tf.argmax(na, 1), tf.argmax(na_predicted, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [101]:
sess = tf.Session()
sess.run(init_op)
total_batch = 15 / batch_size

for epoch in range(100):
    avg_cost = 0
    for i in range(int(100)):
        _,c = sess.run([optimiser,cross_entropy],
                       feed_dict={es:es,na:na})
        avg_cost += c / total_batch
        print("Epoch:", (epoch + 1), "cost =", "{:.3f}".format(avg_cost))

TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.